name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/staging'
    steps:
      - uses: actions/checkout@v4
      - run: npm install && npm run build
      - name: Create .env from appropriate ENV_FILE
        run: echo "${{ secrets.PROD_ENV_FILE }}" | base64 --decode > .env

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_XUMTECH_CHATBOT }}
          projectId: xumtech-chatbot
          channelId: live
          target: xumtech-chatbot
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks
